### ISSUE TITLE
Refactor Login/Register screens to use `React Native Elements` & better form validation

### ISSUE THREAD

**Issue by DemiKnight** [DemiKnight/mad-coursework#9]
# Pre-flight:
- [ ] UI framework chosen
- [ ] Form Validation approach decided/implemented #8

# TODO
- [ ] Utilise UI framework components for buttons & text/layout.
- [ ] Implement form validation 
- [ ] Revisit how state is passed between components/screens. Maybe use `Ref`?
